### ISSUE TITLE
Handling randomness in test results

### ISSUE THREAD

**Issue by ajirnyiqrm** [Paul-Haimerl/BTtest#3]
Sorry -- just accidentally came across your package because it was recently updated on CRAN, and wanted to check whether it might help with something I was working on. So this question is probably not so much an issue per se as just me not being familiar with the theory involved.
 
But, is it expected that the results are not deterministic? If it is, it might be worth mentioning in the package documentation (or if there is some parameter like the number of simulations that can help, perhaps it could be exposed in the API?)
```
X <- sim_DGP(N = 100, n_Periods = 200)
bb <- t(sapply(1:100, function(x) BTtest(X = X, r_max = 10, alpha = 0.05, BT1 = TRUE)))
nrow(unique(bb))  # 4
```

**Comment by Paul-Haimerl** [comment]
Hey,

many thanks for reaching out.

Yes indeed, the results are not deterministic. The test builds on draws from a random variable to obtain the distribution of the test statistic. 
In a practical applications, this randomness can be eliminated using a `set.seed()` command, prior to invoking `BTtest()`. 
But I agree that this characteristic may not be apparent for users unfamiliar with the underlying theory. Also good idea with making the number of draws that build the test statistic an explicit argument. I will include these two remarks in the next update.

Feel free to reach out in case anything else is unclear.

Best,
Paul

**Comment by ajirnyiqrm** [comment]
No problem, thanks for the clarification!
